### ISSUE TITLE
Not issue, I need help

### ISSUE THREAD

**Issue by petarkozic** [fabxc/jiralerts#4]
@fabxc Hi Fab, thank you for yours api.

Please, can you tell me how to integrate that. Where I must to put this python api ? I'm using alertmanger in docker. Some specific folder on alertmanager machine ?

I understand this for config file, but I don't know where I must to import this python script.
Thank you in advanced.

**Comment by andrewhowdencom** [comment]
Hola @petarkozic;

You will get heaps faster and better answers on the mailing list. Check out https://prometheus.io/community/

I daresay this issue will be closed -- they tend to be pretty strict on the "send help to mailing list plz".

**Comment by fabxc** [comment]
Closing as you moved it to the mailing list and got answers there.
@andrewhowdencom thanks for pointing people into the right direction :)

Thread for future reference: https://groups.google.com/forum/#!topic/prometheus-users/vYRROW6i0xg
